version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: dogs-db
    environment:
      POSTGRES_USER: dogs
      POSTGRES_PASSWORD: dogs
      POSTGRES_DB: dogs
    ports:
      - "5432:5432"
